add option to allow sm.px to cross antimeridian
mapbox/sphericalmercator pull request #44
Opened 2021-09-20 18:30 UTC by riastrad

Resolves https://github.com/mapbox/sphericalmercator/issues/41

Previously, `@mapbox/sphericalmercator` would clamp pixels so that it's calculations would not cross the anti-meridian. However, in some cases, clients may prefer to allow calculations to cross the anti-meridian. For example, in instances when their mapping library is able to handle longitudes values that are >180°.

This PR introduces a new option, `antimeridian`, that can be passed when initializing a `SphericalMercator` object. By default this option's value is `false`. However, when it is set to `true` it allows the `SphericalMercator.prototype.px()` method to calculate pixel values for longitude values up to 360°. 

cc/ @mapbox/static-apis

2021-09-20 21:05 UTC, shabnomnom requested changes

2021-09-20 21:05 UTC, shabnomnom commented on sphericalmercator.js
> +    this.expansion = (options.antimeridian === true) ? 2 : 1;
I like this flagging approach a lot!

2021-09-21 14:44 UTC, riastrad commented on test/sphericalmercator.test.js
> +        [6599, 2014],
👍 https://github.com/mapbox/sphericalmercator/pull/44/commits/8e837427e8104c191fda572a603fab6e991d3e1a

2021-09-21 16:09 UTC, mapsam approved these changes
LGTM @riastrad! Thanks for keeping this backwards compatible. Can you update the `px` docs to note that if `antimeridian: true` is set, you'll wrap once?

2021-09-21 18:36 UTC, shabnomnom approved these changes

2021-09-21 19:44 UTC, merged